name: codspeed-benchmarks
'on':
  push:
    branches:
    - master
  pull_request: null
  workflow_dispatch: null
jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup rust toolchain, cache and cargo-codspeed binary
      uses: moonrepo/setup-rust@dcab3dcf9f278945f3f983bace1c7c84033433a7
      with:
        cache-target: release
        bins: cargo-codspeed
    - name: Build the benchmark target(s)
      run: 'cargo codspeed build -p arrow --features test_utils,csv,json,chrono-tz,pyarrow,prettyprint

        cargo codspeed build -p parquet --features arrow,test_common,experimental,default

        cargo codspeed build -p arrow-array -p arrow-buffer -p arrow-cast -p arrow-json

        '
    - name: Run the benchmarks
      uses: CodSpeedHQ/action@ab07afd34cbbb7a1306e8d14b7cc44e029eee37a
      with:
        upload-url: ${{ secrets.CODSPEED_STAGING_UPLOAD_URL }}
        run: cargo codspeed run
